 name: Deploy using SFTP

 on:
   push:
     branches:
       - main  # Spustí se pouze při pushi do větve 'main'

 jobs:
   mirror_with_sftp:
     name: deploy
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: FTP Deployer
         uses: AbleLincoln/push-to-sftp@v2.1
         with:
             host: ${{ secrets.SERVER_HOST }}
             port: 2222
             username: ${{ secrets.SERVER_USERNAME }}
             password: ${{ secrets.SERVER_PASSWORD }}
             sourceDir: ./
             targetDir: /
